import figma from "@figma/code-connect";
import React from "react";

import { DrawerRoot } from "./Drawer";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DrawerRoot,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10752%3A16973",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "status": figma.enum('Status', {
      //   "Default": "default"
      // })
    },
    example: (props) => (
      <DrawerRoot open={/* TODO */} onOpenChange={/* TODO */} />
    ),
  },
);
