import figma from "@figma/code-connect";
import React from "react";

import { UnderlinedLink } from "./UnderlinedLink";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  UnderlinedLink,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=9305%3A16560",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text'),
      // "status": figma.enum('status', {
      //   "default": "default",
      //   "hover": "hover"
      // }),
      // "hasIcon": figma.boolean('hasIcon')
    },
    example: (props) => (
      <UnderlinedLink href={/* TODO */} openInNewTab={/* TODO */} />
    ),
  },
);
