FROM prom/prometheus:latest AS prometheus

FROM alpine:3.19
ARG CACHEBUST=1
RUN apk add --no-cache gettext
COPY --from=prometheus /bin/prometheus /bin/prometheus
COPY --from=prometheus /bin/promtool /bin/promtool
COPY --from=prometheus /etc/prometheus /etc/prometheus
COPY prometheus.yml /etc/prometheus/prometheus.yml.tmpl
COPY alerts.yml /etc/prometheus/alerts.yml
COPY entrypoint.prometheus.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
