receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlp_grpc/tempo:
    endpoint: ${TEMPO_ENDPOINT}
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: ${LOKI_ENDPOINT}/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
