import figma from "@figma/code-connect";
import React from "react";

import { DefaultLink } from "./DefaultLink";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DefaultLink,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=5740%3A7077",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      scroll: figma.enum("Status", {
        Hover: true,
      }),
      className: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      // "label": figma.string('Label'),
      // "isHighlight": figma.boolean('isHighlight'),
      // "hasIcon": figma.boolean('hasIcon'),
      // "isSmall": figma.boolean('isSmall')
    },
    example: (props) => (
      <DefaultLink
        href={/* TODO */}
        scroll={props.scroll}
        openInNewTab={/* TODO */}
        className={props.className}
      />
    ),
  },
);
