import "./globals.css";
import "tailwindcss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProviders } from "@/components/providers/global-provider";
import { ReactNode } from "react";
import { HeaderSidebar } from "@/components/ui/header-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-darkest overflow-x-hidden xl:overflow-hidden`}
      >
        <GlobalProviders>
          <HeaderSidebar />
          <div className="xl:ml-[330px] xl:overflow-auto xl:max-h-screen">
            {children}
          </div>
        </GlobalProviders>
      </body>
    </html>
  );
}
