import "./globals.css";
import "tailwindcss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProviders } from "@/components/providers/global-provider";
import { ReactNode } from "react";
import { ConnectWallet } from "@/components/ui/connect-wallet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-foreground overflow-x-hidden`}>
        <GlobalProviders>
          <div className="md:flex">
            <header className="z-50 sticky top-0 left-0 bg-light md:max-w-[330px] w-screen items-center justify-between md:h-screen shadow-lg flex md:flex-col space-y-0 space-x-6 md:space-x-0 md:space-y-12 md:items-start md:justify-start p-6 md:p-10">
              <h1 className="font-bold text-xl text-accentColored">
                Governance dashboard
              </h1>
              <ConnectWallet />
            </header>
            {children}
          </div>
        </GlobalProviders>
      </body>
    </html>
  );
}
