/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "APIGateway": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "AnticaptureDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "CoingeckoAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DuneAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DuneAPIUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EnsIndexer": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "EnsIndexerAPI": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "EthereumRPC": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "anticapture-vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}