import figma from "@figma/code-connect";
import React from "react";

import { BlankSlate } from "./BlankSlate";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BlankSlate,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10744%3A9884",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("description"),
      className: figma.string("description"),
      description: figma.string("description"),
      // No matching props could be found for these Figma properties:
      // "description": figma.string('description'),
      // "icon": figma.instance('Icon'),
      // "type": figma.enum('type', {
      //   "default": "default",
      //   "small": "small",
      //   "title": "title",
      //   "title + btn": "title---btn"
      // })
    },
    example: (props) => (
      <BlankSlate
        variant={/* TODO */}
        icon={/* TODO */}
        title={props.title}
        className={props.className}
        description={props.description}
      />
    ),
  },
);
