import figma from "@figma/code-connect";
import React from "react";

import { Tooltip } from "./Tooltip";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=11215%3A51940",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('type', {
      //   "default": "default",
      //   "title": "title",
      //   "chart": "chart",
      //   "topics": "topics"
      // })
    },
    example: (props) => <Tooltip tooltipContent={/* TODO */} />,
  },
);
