import figma from "@figma/code-connect";
import React from "react";

import { DrawerHeader } from "./DrawerHeader";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DrawerHeader,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10752%3A17019",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "hasTabs": figma.boolean('hasTabs'),
      // "hasSubtitle": figma.boolean('hasSubtitle')
    },
    example: (props) => <DrawerHeader title={""} onClose={() => {}} />,
  },
);
