import figma from "@figma/code-connect";
import React from "react";

import { Button } from "./Button";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10706%3A742",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "status": figma.enum('status', {
      //   "Default": "default",
      //   "hover": "hover"
      // })
    },
    example: (props) => <Button />,
  },
);
