import React, { useEffect, useState } from "react";
import useBaseUrl from "@docusaurus/useBaseUrl";
import clsx from "clsx";

// A custom navbar item: an "LLM Docs" dropdown exposing the Markdown artifacts
// generated by `@signalwire/docusaurus-plugin-llms-txt`. Reuses Docusaurus's
// native navbar/menu classes so it matches the rest of the navbar.
//
// `llms-full.txt` / `llms.txt` only exist in a production build, so the copy
// and view actions are inert in `docusaurus start`.

type Props = { mobile?: boolean };

export default function LlmDocsNavbarItem({
  mobile = false,
}: Props): React.JSX.Element {
  const llmsFull = useBaseUrl("/llms-full.txt");
  const llmsIndex = useBaseUrl("/llms.txt");

  // Absolute URL is only knowable in the browser; assistants need it to fetch.
  const [origin, setOrigin] = useState("");
  const [copied, setCopied] = useState(false);
  useEffect(() => setOrigin(window.location.origin), []);

  const fullAbsUrl = origin ? `${origin}${llmsFull}` : llmsFull;
  const prompt = `Read the Anticapture MCP documentation at ${fullAbsUrl} and help me use it.`;
  const chatgptUrl = `https://chatgpt.com/?q=${encodeURIComponent(prompt)}`;
  const claudeUrl = `https://claude.ai/new?q=${encodeURIComponent(prompt)}`;

  const copyEntireDocs = async (e: React.MouseEvent) => {
    e.preventDefault();
    try {
      const res = await fetch(llmsFull);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      await navigator.clipboard.writeText(await res.text());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* file absent (dev) or clipboard blocked - no-op */
    }
  };

  const links = (linkClass: string) => (
    <>
      <li>
        <a className={linkClass} href={llmsFull} onClick={copyEntireDocs}>
          {copied ? "Copied!" : "Copy entire docs (Markdown)"}
        </a>
      </li>
      <li>
        <a
          className={linkClass}
          href={llmsFull}
          target="_blank"
          rel="noopener noreferrer"
        >
          View as Markdown (llms-full.txt)
        </a>
      </li>
      <li>
        <a
          className={linkClass}
          href={llmsIndex}
          target="_blank"
          rel="noopener noreferrer"
        >
          View index (llms.txt)
        </a>
      </li>
      <li>
        <a
          className={linkClass}
          href={chatgptUrl}
          target="_blank"
          rel="noopener noreferrer"
        >
          Open in ChatGPT
        </a>
      </li>
      <li>
        <a
          className={linkClass}
          href={claudeUrl}
          target="_blank"
          rel="noopener noreferrer"
        >
          Open in Claude
        </a>
      </li>
    </>
  );

  // Mobile: render as a flat section in the slide-out menu.
  if (mobile) {
    return (
      <li className="menu__list-item">
        <div className="menu__list-item-collapsible">
          <span className="menu__link">LLM Docs</span>
        </div>
        <ul className="menu__list">{links("menu__link")}</ul>
      </li>
    );
  }

  // Desktop: a hoverable navbar dropdown.
  return (
    <div
      className={clsx(
        "navbar__item",
        "dropdown",
        "dropdown--hoverable",
        "dropdown--right",
      )}
    >
      <a
        href="#"
        className="navbar__link"
        onClick={(e) => e.preventDefault()}
        aria-haspopup="true"
      >
        LLM Docs
      </a>
      <ul className="dropdown__menu">{links("dropdown__link")}</ul>
    </div>
  );
}
