import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import type * as OpenApiPlugin from "docusaurus-plugin-openapi-docs";

// The MCP server (mcp-server.ts / mcp-server-http.ts) exposes the Anticapture
// Gateful API as MCP tools. Those tools are generated by Kubb from the same
// OpenAPI spec rendered here, so each operation below maps 1:1 to an MCP tool
// (operationId -> tool name, OpenAPI tag -> tool group).
const GATEFUL_SPEC = "../../../apps/gateful/openapi/gateful.json";

const config: Config = {
  title: "Anticapture MCP DOcs",
  tagline: "MCP server for Anticapture DAO governance analytics",

  url: "https://anticapture.xyz",
  // Served behind the infra/proxy reverse proxy under the /docs prefix. This
  // must match the proxy's `location /docs/` so Docusaurus emits asset URLs
  // (/docs/assets/...) that resolve through the proxy.
  baseUrl: "/docs/",

  organizationName: "blockful-io",
  projectName: "anticapture",

  // The generated OpenAPI MDX is rich; treat broken links as errors but keep
  // markdown-link checks lenient until the hand-written guide is fleshed out.
  onBrokenLinks: "warn",
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          docItemComponent: "@theme/ApiItem",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "openapi",
        docsPluginId: "classic",
        config: {
          mcp: {
            specPath: GATEFUL_SPEC,
            outputDir: "docs/tools",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          } satisfies OpenApiPlugin.Options,
        },
      },
    ],
  ],

  themes: [
    "docusaurus-theme-openapi-docs",
    // Build-time, fully offline search index (no external service). Indexes
    // both the hand-written guide and the generated tool pages. Note: search
    // only works against a production `build`, not the dev server.
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: "Anticapture MCP Docs",
      items: [
        {
          type: "doc",
          docId: "intro",
          position: "left",
          label: "Guide",
        },
        {
          href: "https://github.com/blockful-io/anticapture",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      copyright: `Anticapture MCP powered by <a href="https://blockful.io" target="_blank" rel="noopener noreferrer">blockful</a>`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
