import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import type * as OpenApiPlugin from "docusaurus-plugin-openapi-docs";

// The site documents the whole Anticapture API surface: the Gateful REST API,
// the MCP server (whose tools are generated by Kubb from the same Gateful
// OpenAPI spec rendered here — operationId -> tool name, tag -> tool group),
// and the standalone Webhook Notification API.
//
// Both spec paths point at filtered copies produced by
// `scripts/prepare-spec.mjs` (run before gen-api-docs), which strips the
// unsupported relayer endpoints and internal marker tags from the Gateful
// spec. They are gitignored and regenerated on every build.
const GATEFUL_SPEC = "./openapi/gateful.json";
const WEBHOOK_SPEC = "./openapi/webhook.json";

const config: Config = {
  title: "Anticapture API Docs",
  tagline: "REST API, MCP server, and webhooks for DAO governance analytics",
  // Resolved against static/ and prefixed with baseUrl -> /docs/img/favicon.svg
  favicon: "img/favicon.svg",

  url: "https://anticapture.xyz",
  // Served behind the infra/proxy reverse proxy under the /docs prefix. This
  // must match the proxy's `location /docs/` so Docusaurus emits asset URLs
  // (/docs/assets/...) that resolve through the proxy.
  baseUrl: "/docs/",

  organizationName: "blockful-io",
  projectName: "anticapture",

  // The generated OpenAPI MDX is rich; treat broken links as errors but keep
  // markdown-link checks lenient until the hand-written guide is fleshed out.
  onBrokenLinks: "warn",
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          docItemComponent: "@theme/ApiItem",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "openapi",
        docsPluginId: "classic",
        config: {
          api: {
            specPath: GATEFUL_SPEC,
            outputDir: "docs/api-reference",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          } satisfies OpenApiPlugin.Options,
          webhook: {
            specPath: WEBHOOK_SPEC,
            outputDir: "docs/webhooks/reference",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          } satisfies OpenApiPlugin.Options,
        },
      },
    ],
    // The reference lived under /docs/tools/ when the site was MCP-only.
    // Redirect those URLs (still held by users, search engines, and LLM
    // indexes) to the same pages under /api-reference/.
    [
      "@docusaurus/plugin-client-redirects",
      {
        createRedirects: (existingPath: string) => {
          if (existingPath.includes("/api-reference/")) {
            return [existingPath.replace("/api-reference/", "/tools/")];
          }

          return undefined;
        },
        redirects: [
          // The old MCP getting-started guide is now the MCP section.
          { from: "/guide/getting-started", to: "/mcp" },
        ],
      },
    ],
    // Generate LLM-friendly Markdown from the rendered HTML at build time:
    // `/llms.txt` (index), `/llms-full.txt` (entire docs as one file), and a
    // `.md` mirror of every page (used by the "Copy as Markdown" button).
    // Works on built HTML, so it handles the generated reference pages too.
    [
      "@signalwire/docusaurus-plugin-llms-txt",
      {
        content: {
          enableMarkdownFiles: true,
          enableLlmsFullTxt: true,
          includeDocs: true,
        },
        depth: 1,
        siteTitle: "Anticapture API Docs",
        siteDescription:
          "Anticapture DAO governance analytics: REST API reference, MCP server, and webhook notifications",
      },
    ],
  ],

  themes: [
    "docusaurus-theme-openapi-docs",
    // Build-time, fully offline search index (no external service). Indexes
    // both the hand-written guides and the generated reference pages. Note:
    // search only works against a production `build`, not the dev server.
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    // Match the Anticapture dashboard identity: the product is dark-first.
    colorMode: {
      defaultMode: "dark",
      respectPrefersColorScheme: false,
    },
    // Restrict the generated request-sample tabs. The OpenAPI theme can only
    // emit languages supported by postman-code-generators, which has no
    // TypeScript target — `nodejs`/Axios is the closest stand-in for TS.
    languageTabs: [
      {
        highlight: "bash",
        language: "curl",
        logoClass: "curl",
      },
      {
        highlight: "javascript",
        language: "nodejs",
        logoClass: "nodejs",
        variant: "Axios",
      },
      {
        highlight: "rust",
        language: "rust",
        logoClass: "rust",
        variant: "reqwest",
      },
      { highlight: "go", language: "go", logoClass: "go", variant: "Native" },
    ],
    navbar: {
      title: "Anticapture",
      items: [
        {
          type: "doc",
          docId: "getting-started",
          position: "left",
          label: "Getting started",
        },
        {
          type: "doc",
          docId: "api-reference/anticapture-gateful-rest-api",
          position: "left",
          label: "API Reference",
        },
        {
          type: "doc",
          docId: "mcp/index",
          position: "left",
          label: "MCP",
        },
        {
          type: "doc",
          docId: "webhooks/index",
          position: "left",
          label: "Webhooks",
        },
        {
          type: "custom-llmDocs",
          position: "right",
        },
        {
          href: "https://github.com/blockful-io/anticapture",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      copyright: `Anticapture powered by <a href="https://blockful.io" target="_blank" rel="noopener noreferrer">blockful</a>`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
