import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Loose item shape: the generated sidebars are plain data validated by
// Docusaurus at load time, so mirroring the full SidebarItemConfig union here
// buys nothing.
type SidebarItem = {
  type: string;
  items?: SidebarItem[];
  [k: string]: unknown;
};

// The OpenAPI plugin writes tag-grouped sidebars (categories with HTTP-method
// badges) into the generated output dirs. Those files only exist after
// `gen-api-docs` has run — every start/build script runs it first — so fall
// back to plain directory autogeneration to keep editor tooling and a fresh
// checkout from crashing on the missing module.
const generatedSidebar = (path: string, fallbackDir: string): SidebarItem[] => {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(path).default;
  } catch {
    return [{ type: "autogenerated", dirName: fallbackDir }];
  }
};

// First generated item is the spec info page — it becomes the category link
// below (its own `sidebar_label: Introduction` cannot be overridden from
// here); the rest are the tag-grouped endpoint categories.
const [, ...apiGroups] = generatedSidebar(
  "./docs/api-reference/sidebar",
  "api-reference",
);

// Flatten the webhook reference to just its operation docs; the info page
// becomes the category link instead of a loose sidebar entry.
const webhookReference = generatedSidebar(
  "./docs/webhooks/reference/sidebar",
  "webhooks/reference",
);
const webhookOperations = webhookReference.flatMap((item) =>
  item.type === "category" && item.items ? item.items : [],
);

// One sidebar for the whole site: guides as top-level items, the API
// reference as an accordion of tag groups — mirroring the dashboard's single
// accordion sidebar.
const sidebars = {
  docs: [
    { type: "doc", id: "index", label: "Introduction" },
    { type: "doc", id: "getting-started", label: "Getting started" },
    { type: "doc", id: "mcp/index", label: "MCP server" },
    { type: "doc", id: "webhooks/index", label: "Webhooks" },
    {
      type: "category",
      label: "API Reference",
      collapsed: false,
      link: { type: "doc", id: "api-reference/anticapture-rest-api" },
      items: [
        ...apiGroups,
        {
          type: "category",
          label: "Webhook API",
          collapsed: true,
          link: {
            type: "doc",
            id: "webhooks/reference/webhook-notification-api",
          },
          items: webhookOperations.length
            ? webhookOperations
            : webhookReference,
        },
      ],
    },
  ],
} as SidebarsConfig;

export default sidebars;
