import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// A single autogenerated sidebar over the whole docs/ tree. This deliberately
// avoids importing the OpenAPI plugin's generated `docs/tools/sidebar.ts`,
// which does not exist until `gen-api-docs` has run — autogeneration picks up
// the hand-written guide and the generated tool pages alike.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
