import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Explicit top-level ordering (landing -> getting started -> reference ->
// MCP -> webhooks); the generated reference folders are autogenerated because
// their pages do not exist until `gen-api-docs` has run. This deliberately
// avoids importing the OpenAPI plugin's generated `sidebar.ts` files.
const sidebars: SidebarsConfig = {
  docs: [
    "index",
    "getting-started",
    {
      type: "category",
      label: "API Reference",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "api-reference" }],
    },
    "mcp/index",
    {
      type: "category",
      label: "Webhooks",
      collapsed: false,
      link: { type: "doc", id: "webhooks/index" },
      items: [{ type: "autogenerated", dirName: "webhooks/reference" }],
    },
  ],
};

export default sidebars;
