// Better-auth core tables (user, session, account, verification, and the SIWE
// plugin's walletAddress table) are generated by the better-auth CLI:
//
//   pnpm --filter @anticapture/user-api auth:generate
//
// The User API runs on its own Postgres database (default `public` schema), so the
// CLI's unqualified output works as-is — no pgSchema namespacing needed.
// Domain tables (drafts, user settings) are added alongside this re-export in a
// later step.
export * from "./auth-schema";
