import { sql } from "drizzle-orm";
import {
  bigint,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Better-auth core tables (user, session, account, verification, and the SIWE
// plugin's walletAddress table) are generated by the better-auth CLI:
//
//   pnpm --filter @anticapture/user-api auth:generate
//
// The User API runs on its own Postgres database (default `public` schema), so
// the CLI's unqualified output works as-is — no pgSchema namespacing needed.
export * from "./auth-schema";

export const drafts = pgTable(
  "drafts",
  {
    // Server-generated: a client-chosen id would let a malicious caller mint
    // guessable share links (the id is the share capability).
    id: uuid("id").primaryKey().defaultRandom(),
    // Owner. Null only for rows migrated from the DAO APIs whose author
    // wallet has not signed in yet — claimed on first SIWE login via
    // authorAddress (see DraftsService.claimForUser).
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    // Wallet that authored the draft, when known (SIWE authors and migrated
    // rows): display + claim key. Null for email/Google authors.
    authorAddress: text("author_address"),
    daoId: text("dao_id").notNull(),
    title: text("title").notNull().default(""),
    discussionUrl: text("discussion_url").notNull().default(""),
    body: text("body").notNull().default(""),
    actions: jsonb("actions")
      .notNull()
      .default(sql`'[]'::jsonb`),
    // Unix milliseconds, matching the DAO API rows these migrate from.
    createdAt: bigint("created_at", { mode: "number" }).notNull(),
    updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
  },
  (table) => [
    index().on(table.userId, table.daoId),
    index().on(table.authorAddress),
  ],
);

// Ownership record for user-minted API keys. The plaintext and hash live only
// in Authful (tenant `user:<userId>`); here we keep just who owns which Authful
// token, plus the user's label. Never stores secrets.
export const userApiKeys = pgTable(
  "user_api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    authfulTokenId: uuid("authful_token_id").notNull(),
    label: text("label").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
  },
  (table) => [index().on(table.userId)],
);
