/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Anticapture-ENS-DB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "Anticapture-UNI-DB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "ENSIndexer": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "EthereumRPC": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UNIIndexer": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "anticapture-vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}