import figma from "@figma/code-connect";
import React from "react";

import { InlineAlert } from "./InlineAlert";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InlineAlert,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=9307%3A16583",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      text: figma.string("text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text'),
      // "hasLink": figma.boolean('hasLink')
    },
    example: (props) => <InlineAlert text={props.text} variant={"info"} />,
  },
);
