import figma from "@figma/code-connect";
import React from "react";

import { TableCell } from "./TableCell";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TableCell,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10713%3A21467",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('Type', {
      //   "title": "title",
      //   "text": "text",
      //   "variation": "variation",
      //   "chart": "chart",
      //   "badge": "badge",
      //   "user/dao": "user-dao",
      //   "clickable": "clickable",
      //   "progress": "progress",
      //   "multiple badges": "multiple-badges",
      //   "button": "button",
      //   "bar": "bar",
      //   "copy address": "copy-address"
      // }),
      // "hasHover": figma.boolean('hasHover')
    },
    example: (props) => <TableCell />,
  },
);
