import figma from "@figma/code-connect";
import React from "react";

import { Toast } from "./Toast";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=16695%3A59225",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      message: figma.string("text"),
      type: figma.enum("type", {
        success: "success",
        error: "error",
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text'),
      // "icon": figma.instance('icon')
    },
    example: (props) => (
      <Toast
        message={props.message}
        type={props.type}
        visible={/* TODO */}
        onClose={/* TODO */}
      />
    ),
  },
);
