import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

const PONDER_SCHEMA_PATH = path.join(__dirname, "../ponder.schema.ts");
const API_SCHEMA_PATH = path.join(__dirname, "../src/api/schema/generated.ts");

function generateApiSchema(): void {
  console.log("🔄 Generating API schema from Ponder schema...");

  let content = fs.readFileSync(PONDER_SCHEMA_PATH, "utf-8");

  // Replace imports from ponder
  content = content.replace(/import\s*{[^}]*}\s*from\s*["']ponder["'];?/g, "");

  // Replace onchainTable with pgTable
  content = content.replace(/onchainTable\(/g, "pgTable(");

  // Replace onchainEnum with pgEnum
  content = content.replace(/onchainEnum\(/g, "pgEnum(");

  // Replace drizzle parameter - but NOT in strings
  // Replace (drizzle) => with (t) =>
  content = content.replace(/\(drizzle\)\s*=>/g, "(t) =>");
  // Replace drizzle. with t. (property access)
  content = content.replace(/\bdrizzle\./g, "t.");

  // Handle bigint - add mode: "bigint" to all bigint columns
  content = content.replace(/\.bigint\(\)/g, '.bigint({ mode: "bigint" })');
  content = content.replace(
    /\.bigint\(["']([^"']+)["']\)/g,
    '.bigint("$1", { mode: "bigint" })',
  );

  // Convert composite primary keys and indexes from object to array syntax
  content = content.replace(
    /\(table\)\s*=>\s*\(\{\s*([\s\S]*?)\s*\}\),?\s*\);/g,
    (match, objectContent) => {
      const lines: string[] = [];
      let depth = 0;
      let currentLine = "";
      let inPropertyName = true;

      for (let i = 0; i < objectContent.length; i++) {
        const char = objectContent[i];

        if (char === ":" && depth === 0 && inPropertyName) {
          inPropertyName = false;
          currentLine = "";
          continue;
        }

        if (char === "{" || char === "[") depth++;
        if (char === "}" || char === "]") depth--;

        if (char === "," && depth === 0) {
          if (currentLine.trim()) {
            lines.push(currentLine.trim());
          }
          currentLine = "";
          inPropertyName = true;
          continue;
        }

        if (!inPropertyName) {
          currentLine += char;
        }
      }

      if (currentLine.trim()) {
        lines.push(currentLine.trim());
      }

      const values = lines.join(",\n  ");
      return `(table) => [\n  ${values}\n]);`;
    },
  );

  // Remove all relation exports
  content = content.replace(
    /export\s+const\s+\w+Relations\s*=\s*relations\([^;]+\);/gs,
    "",
  );

  // Remove relation-related comments
  content = content.replace(/\/\/.*relations?\s*$/gim, "");

  // Clean up multiple empty lines
  content = content.replace(/\n{3,}/g, "\n\n");

  // Add new imports at the top (AFTER all replacements to avoid corruption)
  const newImports = `import { pgTable, pgEnum, text, integer, bigint, boolean, json, index, primaryKey } from "drizzle-orm/pg-core";
`;

  // Find the position after existing imports
  const importMatch = content.match(/import[^;]+;/g);
  if (importMatch && importMatch.length > 0) {
    const lastImport = importMatch[importMatch.length - 1]!;
    const lastImportIndex = content.lastIndexOf(lastImport);
    const insertPosition = content.indexOf(";", lastImportIndex) + 1;
    content =
      content.slice(0, insertPosition) +
      "\n" +
      newImports +
      content.slice(insertPosition);
  } else {
    content = newImports + "\n" + content;
  }

  // Add warning comment at the top
  const warning = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated from ponder.schema.ts
 * Run 'npm run generate:schema' to regenerate
 * 
 * Last generated: ${new Date().toISOString()}
 */

`;

  content = warning + content;

  // Ensure directory exists
  const dir = path.dirname(API_SCHEMA_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Write the file
  fs.writeFileSync(API_SCHEMA_PATH, content, "utf-8");

  console.log("✅ API schema generated successfully at:", API_SCHEMA_PATH);

  // Run eslint --fix on the generated file
  try {
    console.log("🔧 Running eslint --fix on generated file...");
    execSync(`npx eslint "${API_SCHEMA_PATH}" --fix`, { stdio: "inherit" });
    console.log("✅ Linting completed");
  } catch (error) {
    console.warn("⚠️  Eslint not available or failed, skipping lint step");
  }
}

// Run the function
try {
  generateApiSchema();
} catch (error) {
  console.error("❌ Error generating API schema:", error);
  process.exit(1);
}
