import figma from "@figma/code-connect";
import React from "react";

import { Input } from "./Input";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=21364%3A166",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasIcon: figma.boolean("hasInfo"),
      src: figma.string("Text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text')
    },
    example: (props) => <Input hasIcon={props.hasIcon} src={props.src} />,
  },
);
