import figma from "@figma/code-connect";
import React from "react";

import { SectionTitle } from "./SectionTitle";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SectionTitle,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10339%3A58558",
  {
    props: {},
    example: (props) => (
      <SectionTitle icon={<></>} title={""} description={""} />
    ),
  },
);
