import figma from "@figma/code-connect";
import React from "react";

import { SubsectionTitle } from "./SubsectionTitle";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SubsectionTitle,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=11508%3A25396",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      subsectionDescription: figma.string("description"),
      // No matching props could be found for these Figma properties:
      // "description": figma.string('description'),
      // "title": figma.string('title'),
      // "isDescription": figma.boolean('isDescription'),
      // "isDateRange": figma.boolean('isDateRange')
    },
    example: (props) => (
      <SubsectionTitle
        subsectionTitle={""}
        subsectionDescription={props.subsectionDescription}
        dateRange={""}
        switcherComponent={null}
      />
    ),
  },
);
