{
 "title": "eRPC Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "region", "query": { "query": "label_values(region)" } },
   { "name": "project", "query": { "query": "label_values(project)" } },
   { "name": "vendor", "query": { "query": "label_values(vendor)" } },
   { "name": "ignore_vendor", "query": { "query": "label_values(vendor)" } },
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "ignore_network",
    "query": {
     "query": "label_values(erpc_upstream_latest_block_number,network)"
    }
   },
   { "name": "upstream", "query": { "query": "label_values(upstream)" } },
   { "name": "user", "query": { "query": "label_values(user)" } },
   { "name": "category", "query": { "query": "label_values(category)" } },
   { "name": "finality", "query": { "query": "label_values(finality)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Share Breakdown (Top 20)",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(200,\n  sum by (region, network, vendor, finality, category) (\n    increase(erpc_network_successful_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      user=~\"${user:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{region}}, {{network}}, {{vendor}}, {{finality}}, {{category}}"
      }
     ]
    },
    {
     "title": "Vendors Share (Top 20)",
     "type": "piechart",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 2252 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (vendor) (\n    increase(erpc_network_successful_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\",\n      user=~\"${user:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{upstream}} {{vendor}} {{category}}"
      }
     ]
    },
    {
     "title": "Upstreams Share (Top 20)",
     "type": "piechart",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 2252 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (upstream) (\n    increase(erpc_upstream_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\",\n      user=~\"${user:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{upstream}} {{vendor}} {{category}}"
      }
     ]
    },
    {
     "title": "Networks Share (Top 20)",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 8, "x": 0, "y": 2271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (region, network) (\n    increase(erpc_network_successful_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\",\n      user=~\"${user:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{region}} {{network}}"
      }
     ]
    },
    {
     "title": "Method Share (Top 20)",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 8, "x": 8, "y": 2271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (category) (\n    increase(erpc_network_successful_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\",\n      user=~\"${user:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{region}} {{category}}"
      }
     ]
    },
    {
     "title": "Finality Share (Top 20)",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 8, "x": 16, "y": 2271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (finality, vendor) (\n    increase(erpc_network_successful_request_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\",\n      network=~\"${network:regex}\",\n      network!~\"${ignore_network:regex}\",\n      project=~\"${project:regex}\",\n      vendor=~\"${vendor:regex}\",\n      vendor!~\"${ignore_vendor:regex}\",\n      category=~\"${category:regex}\",\n      finality=~\"${finality:regex}\",\n      user=~\"${user:regex}\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{vendor}} {{finality}}"
      }
     ]
    },
    {
     "title": "Total Responses (by Region and User-Agent)",
     "type": "timeseries",
     "description": "Total successful responses sent back to the client",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 2584 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_successful_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    project=~\"${project:regex}\",\n    vendor=~\"${vendor:regex}\",\n    upstream=~\"${upstream:regex}\",\n    vendor!~\"${ignore_vendor:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\",user=~\"${user:regex}\"\n    }[1m])) by (region, agent_name, user) > 0",
       "legendFormat": "{{region}} {{agent_name}} {{user}}"
      }
     ]
    },
    {
     "title": "Total Responses (by Region)",
     "type": "timeseries",
     "description": "Total successful responses sent back to the client",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 2584 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_successful_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    project=~\"${project:regex}\",\n    vendor=~\"${vendor:regex}\",\n    upstream=~\"${upstream:regex}\",\n    vendor!~\"${ignore_vendor:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\",user=~\"${user:regex}\"\n    }[1m])) by (region) > 0",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks - Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Requests",
     "type": "timeseries",
     "description": "Total requests received by eRPC for a specific network and method",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_request_received_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    network!~\"${ignore_network:regex}\",\n    upstream=~\"${upstream:regexp}\",\n    category=~\"${category:regex}\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (region, network, category, finality)",
       "legendFormat": "{{region}}, {{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Incoming RPS",
     "type": "timeseries",
     "description": "Total requests received by eRPC for a specific network and method",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_network_request_received_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    network!~\"${ignore_network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[$__rate_interval])) by (region, network, user, category, finality) > 0",
       "legendFormat": "{{region}}, {{network}}, {{user}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Successful Responses RPS",
     "type": "timeseries",
     "description": "Total successful responses sent back to the client",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_network_successful_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    project=~\"${project:regex}\",\n    vendor=~\"${vendor:regex}\",\n    upstream=~\"${upstream:regex}\",\n    vendor!~\"${ignore_vendor:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (region, network, vendor, category, finality, emptyish) > 0",
       "legendFormat": "{{region}} {{network}}, {{vendor}}, {{category}}, {{finality}}, empty={{emptyish}}"
      }
     ]
    },
    {
     "title": "Network-level Critical Errors",
     "type": "timeseries",
     "description": "When a request fails even after trying all upstreams and retries, we send a error response to the user. This chart shows critical errors that need attention and wake-up alarms.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_failed_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    severity=\"critical\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (network,category, finality,error) > 0",
       "legendFormat": "{{network}}, {{category}}, {{finality}}, {{error}}"
      }
     ]
    },
    {
     "title": "Network-level Warnings",
     "type": "timeseries",
     "description": "Issues where clients got an error but it's most probably due to bad requests or a transient problem with upstreams",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_failed_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    severity=\"warning\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (network,category,error,region, user) > 0",
       "legendFormat": "{{region}}, {{network}}, {{category}}, {{error}}"
      }
     ]
    },
    {
     "title": "Network-level Notices",
     "type": "timeseries",
     "description": "Client-side errors where it's most probably a normal operation (eth_call reverts) or bad request by the user",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_failed_request_total{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    severity=\"info\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (network,category,error,user) > 0",
       "legendFormat": "{{network}}, {{category}}, {{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks - Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network-method P99 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    vendor!=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (le, network, category, finality))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Network-method P90 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    vendor!=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (le, network, category, finality))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Network-method P50 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    vendor!=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (le, network, category, finality))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Network-errors P99 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (le, network, category, finality, vendor))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}, {{vendor}}"
      }
     ]
    },
    {
     "title": "Network-errors P90 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\",\n    user=~\"${user:regex}\"\n}[1m])) by (le, network, category, finality, vendor))",
       "legendFormat": "{{network}}, {{category}}, {{vendor}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Network errors P50 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket{\n    cluster=~\"${cluster:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=\"<error>\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (le, network, category, finality, vendor))",
       "legendFormat": "{{network}}, {{category}}, {{vendor}}, {{finality}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks - Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hedge Quantile",
     "type": "timeseries",
     "description": "Current calculated quantile threshold used to trigger hedged requests. This depends on the hedge.quantile and actual latencies (e.g. p70)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "avg(erpc_network_hedge_delay_seconds{network=~\"${network:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}) by (project, network, category, finality)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Hedge RPS",
     "type": "timeseries",
     "description": "Total hedge requests fired due to initial upstream being slow",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_network_hedged_request_total{network=~\"${network:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (project, network, category, finality)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Hedge Effectiveness",
     "type": "timeseries",
     "description": "Total hedged requests that ended up being actually faster and useful. The higher the better. If this value is too low try increasing the failsafe.hedge.quantile to higher value e.g. 0.99",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - ((sum(increase(erpc_network_hedge_discards_total{attempt!=\"1\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[30s])) by (project, network)) / (sum(increase(erpc_network_hedged_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (project, network))) > 0",
       "legendFormat": "{{network}}"
      }
     ]
    },
    {
     "title": "Multiplexed RPS",
     "type": "timeseries",
     "description": "When identical requests arrive at the same time they'll be merged, this number shows number of these requests",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 832 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_network_multiplexed_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (project, network, category, finality)",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Response Finality Share Overall",
     "type": "timeseries",
     "description": "Shows the finality state of the block related to the response, this shows if your workload is mainly around head of chain unfinalized data, or historical finalized data.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 832 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_successful_request_total{network=~\"${network:regex}\",vendor=~\"${vendor:regexp}\",upstream=~\"${upstream:regexp}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (finality)",
       "legendFormat": "{{finality}}"
      }
     ]
    },
    {
     "title": "Response Finality Share By Vendor",
     "type": "timeseries",
     "description": "Shows the finality state of the block related to the response, this shows if your workload is mainly around head of chain unfinalized data, or historical finalized data.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 832 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_network_successful_request_total{network=~\"${network:regex}\",vendor=~\"${vendor:regexp}\",upstream=~\"${upstream:regexp}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (vendor, finality)",
       "legendFormat": "{{vendor}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Highest Finalized Block",
     "type": "timeseries",
     "description": "Highest value for latest block polled from all upstreams across all replicas",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 844 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "max(erpc_upstream_finalized_block_number{upstream=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\"}) by (project, network)",
       "legendFormat": "{{project}}, {{network}}"
      }
     ]
    },
    {
     "title": "Highest Latest Block",
     "type": "timeseries",
     "description": "Highest value for latest block polled from all upstreams across all replicas",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 844 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "max(erpc_upstream_latest_block_number{upstream=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\"}) by (project, network)",
       "legendFormat": "{{project}}, {{network}}"
      }
     ]
    },
    {
     "title": "Block Timestamp Distance - EVM State Poller",
     "type": "timeseries",
     "description": "Comparison of block timestamp distance between EVM State Poller and Network Responses to identify cache staleness and synchronization issues",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 854 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(erpc_network_latest_block_timestamp_distance_seconds{network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",origin=\"evm_state_poller\"}) by (network)",
       "legendFormat": "{{network}}"
      }
     ]
    },
    {
     "title": "Block Timestamp Distance - Network Response",
     "type": "timeseries",
     "description": "Comparison of block timestamp distance between EVM State Poller and Network Responses to identify cache staleness and synchronization issues",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 854 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(erpc_network_latest_block_timestamp_distance_seconds{network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",origin=\"network_response\"}) by (network)",
       "legendFormat": "{{network}}"
      }
     ]
    },
    {
     "title": "Dynamic Block Time",
     "type": "timeseries",
     "description": "Dynamically computed block time per network in seconds. Used to auto-tune the state poller interval and debounce.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 864 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "erpc_network_dynamic_block_time_milliseconds{network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\"}",
       "legendFormat": "{{project}} / {{network}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vendors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vendors Share: finality=$finality",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "repeat": "finality",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (vendor, finality) (\n  erpc_network_successful_request_total{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    network=~\"${network:regex}\",\n    project=~\"${project:regex}\",\n    user=~\"${user:regex}\",\n    vendor=~\"${vendor:regex}\",\n    vendor!=\"n/a\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\"\n  }\n)",
       "legendFormat": "{{vendor}}"
      }
     ]
    },
    {
     "title": "Vendor Requests",
     "type": "timeseries",
     "description": "These are real requests sent to upstream endpoints, including retries, grouped by Vendor Name",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_total{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    project=~\"${project:regex}\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (network, vendor, category)",
       "legendFormat": "{{network}}, {{vendor}}, {{category}}"
      }
     ]
    },
    {
     "title": "Vendor RPS",
     "type": "timeseries",
     "description": "These are real requests sent to upstream endpoints, including retries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_upstream_request_total{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (vendor, category)",
       "legendFormat": "{{network}}, {{vendor}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Upstream-level critical errors",
     "type": "timeseries",
     "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_errors_total{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    severity=\"critical\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (region, project, upstream, category, error) > 0",
       "legendFormat": "{{region}} {{project}}, {{upstream}}, {{category}}, {{error}}"
      }
     ]
    },
    {
     "title": "Vendor warnings",
     "type": "timeseries",
     "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_errors_total{\n    severity=\"warning\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (project, network, vendor, category, finality, error) > 0",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{vendor}}, {{finality}}, {{error}}"
      }
     ]
    },
    {
     "title": "Vendor P99 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\"\n}[1m])) by (le, project, vendor, category))",
       "legendFormat": "{{project}}, {{vendor}}, {{category}}"
      }
     ]
    },
    {
     "title": "Vendor P90 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(erpc_upstream_request_duration_seconds_bucket{\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\"\n}[1m])) by (le, project, vendor, category))",
       "legendFormat": "{{project}}, {{vendor}}, {{category}}"
      }
     ]
    },
    {
     "title": "Vendor P50 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{network=~\"${network:regex}\",vendor=~\"${vendor:regex}\",category=~\"${category:regex}\",composite=\"none\",project=~\"${project:regex}\"}[30s])) by (le, project, vendor, category))",
       "legendFormat": "{{project}}, {{vendor}}, {{category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream-level P99 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (le, project, upstream, category, finality))",
       "legendFormat": "{{project}}, {{upstream}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Upstream-level P90 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(erpc_upstream_request_duration_seconds_bucket{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (le, project, upstream, category, finality))",
       "legendFormat": "{{project}}, {{upstream}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Upstream-level P50 Resp. time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\",\n    finality=~\"${finality:regex}\"\n}[30s])) by (le, project, upstream, category, finality))",
       "legendFormat": "{{project}}, {{upstream}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Upstream-level Requests",
     "type": "timeseries",
     "description": "These are real requests sent to upstream endpoints, including retries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 504 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_total{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category, attempt)",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}, attempt={{attempt}}"
      }
     ]
    },
    {
     "title": "Upstream-level RPS",
     "type": "timeseries",
     "description": "These are real requests sent to upstream endpoints, including retries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 504 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_upstream_request_total{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\",\n    composite=\"none\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category, finality)",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Upstream-level critical errors",
     "type": "timeseries",
     "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 516 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_errors_total{\n    severity=\"critical\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    user=~\"${user:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category, error) > 0",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{upstream}}, {{error}}"
      }
     ]
    },
    {
     "title": "Upstream-level warnings",
     "type": "timeseries",
     "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 516 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_errors_total{\n    severity=\"warning\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category, error) > 0",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{upstream}}, {{error}}"
      }
     ]
    },
    {
     "title": "Upstream wrong empty responses",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 528 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_wrong_empty_response_total{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    user=~\"${user:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category) > 0",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{upstream}}, {{error}}"
      }
     ]
    },
    {
     "title": "Upstream-level notices",
     "type": "timeseries",
     "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 528 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_request_errors_total{\n    severity=\"info\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    user=~\"${user:regex}\",\n    composite=\"none\",\n    vendor=~\"${vendor:regex}\",\n    vendor!~\"${ignore_vendor:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, upstream, category, error) > 0",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{upstream}}, {{error}}"
      }
     ]
    },
    {
     "title": "Upstream stale upper-bound",
     "type": "timeseries",
     "description": "Total number of times a request was skipped due to upstream latest block being less than requested upper bound block",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 537 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_stale_upper_bound_total{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, vendor, upstream, category)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{vendor}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Upstream stale lower-bound",
     "type": "timeseries",
     "description": "Total number of times a request was skipped due to requested lower bound block being less than upstream's available block range.",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 537 },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_stale_lower_bound_total{\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    vendor=~\"${vendor:regex}\",\n    project=~\"${project:regex}\"\n}[1m])) by (project, network, vendor, upstream, category)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{vendor}}, {{upstream}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Primary by Vendor",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "round(avg by (project, network, vendor, category) (\n  erpc_upstream_routing_priority{\n    project=~\"${project:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\"\n  }\n)) * -1",
       "legendFormat": "{{project}}, {{network}}, {{vendor}}, {{category}}"
      }
     ]
    },
    {
     "title": "Primary by Upstream",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "round(avg by (project, network, upstream, category) (\n  erpc_upstream_routing_priority{\n    project=~\"${project:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\"\n  }\n)) * -1",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
      }
     ]
    },
    {
     "title": "Avg. Score by Upstream",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(erpc_upstream_score_overall{\n    project=~\"${project:regex}\",\n    region=~\"${region:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    upstream!=\"n/a\",\n}) by (region, project, upstream, category)",
       "legendFormat": "{{region}}, {{project}}, {{upstream}}, {{category}}"
      }
     ]
    },
    {
     "title": "Avg. Score by Vendor",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg(erpc_upstream_score_overall{\n    region=~\"${region:regex}\",\n    project=~\"${project:regex}\",\n    network=~\"${network:regex}\",\n    vendor=~\"${vendor:regex}\",\n}) by (cluster, region, project, vendor, network, category)",
       "legendFormat": "{{cluster}}, {{region}}, {{project}}, {{network}}, {{project}}, {{vendor}}, {{category}}"
      }
     ]
    },
    {
     "title": "Latest Block Lag by Upstream",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_block_head_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",vendor=~\"${vendor:regex}\"}) by (project, network, upstream) <= 5000",
       "legendFormat": "{{project}},  {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Out-of-sync latest block lag by Upstream",
     "type": "timeseries",
     "description": "A special lagging tracker showing only lags of above 5000 blocks which indicates node too far off.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_block_head_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",vendor=~\"${vendor:regex}\"}) by (project, upstream, network,category) > 5000",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Latest Block by Upstream",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_latest_block_number{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",vendor=~\"${vendor:regex}\",project=~\"${project:regex}\"}) by (project, region, upstream, network)",
       "legendFormat": "{{region}} {{network}} {{vendor}} {{upstream}}"
      }
     ]
    },
    {
     "title": "Latest Block Polls",
     "type": "timeseries",
     "description": "How many times we had to Poll for latest block number. This number can go up by integrity module if debounce config is too low.",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_latest_block_polled_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",vendor=~\"${vendor:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, upstream)",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Finalized Block Lag by Upstream",
     "type": "timeseries",
     "description": "Difference between lowest and highest finalized block as reported by upstreams. Min/Max/Mean are values across multiple replicas (if you have erpc in a multi-container setup)",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_finalization_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",vendor=~\"${vendor:regex}\"}) by (project, upstream, network) <= 5000",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Out-of-sync Finalized Blocks by Upstream",
     "type": "timeseries",
     "description": "A special lagging tracker showing only lags of above 5000 blocks which indicates node too far off.",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_finalization_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",project=~\"${project:regex}\",vendor=~\"${vendor:regex}\"}) by (project, upstream, network) > 5000",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Finalized Block by Upstream",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg(erpc_upstream_finalized_block_number{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\",vendor=~\"${vendor:regex}\",project=~\"${project:regex}\"}) by (project, upstream, network)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finalized Block Polls",
     "type": "timeseries",
     "description": "How many times we had to Poll for finalized block number. ",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_finalized_block_polled_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",vendor=~\"${vendor:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, upstream)",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}"
      }
     ]
    },
    {
     "title": "Stale latest block by Upstream",
     "type": "timeseries",
     "description": "How many times upstream returned a stale latest block (compared to other nodes) for eth_getBlockByNumber(latest) and eth_blockNumber",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_stale_latest_block_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",vendor=~\"${vendor:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, upstream, category)    ",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
      }
     ]
    },
    {
     "title": "Stale finalized block by Upstream",
     "type": "timeseries",
     "description": "How many times upstream returned stale finalized block (compared to other nodes) for eth_getBlockByNumber(finalized) and eth_blockNumber",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_upstream_stale_finalized_block_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, upstream, category)    ",
       "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
      }
     ]
    },
    {
     "title": "Unexpected panics",
     "type": "timeseries",
     "description": "These are issues that are most often edge-cases that are not covered within eRPC logic, and must be reported to the team.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_unexpected_panic_total{project=~\"${project:regex}\"}[1m])) by (scope, extra, error)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Shadow Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shadow Identical",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7314 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_shadow_response_identical_total{project=~\"${project:regexp}\",network=~\"${network:regexp}\"}[1m])) by (project, network, upstream, category, finality)",
       "legendFormat": "{{network}}, {{category}}, {{upstream}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Shadow Mismatches",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7314 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_shadow_response_mismatch_total{project=~\"${project:regexp}\",network=~\"${network:regexp}\"}[1m])) by (project, network, upstream, category, emptyish, larger)",
       "legendFormat": "{{network}}, {{category}}, {{upstream}}, emt={{emptyish}}, lgr={{larger}}"
      }
     ]
    },
    {
     "title": "Shadow Errors",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7326 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_shadow_response_error_total{project=~\"${project:regexp}\",network=~\"${network:regexp}\"}[1m])) by (project, network, upstream, category, finality, error)",
       "legendFormat": "{{network}}, {{category}}, {{upstream}}, {{error}}, {{finality}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache SET success total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1329 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_cache_set_success_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, category, connector)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache SET success duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1329 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_success_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (le, project, network, category, connector))",
       "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache SET error total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1339 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_cache_set_error_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, category, connector, policy, error, ttl)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{error}}, {{policy}}, TTL={{ttl}}"
      }
     ]
    },
    {
     "title": "Cache SET error duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1339 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
       "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_set_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
       "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
      }
     ]
    },
    {
     "title": "Cache GET success-hit total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1349 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_cache_get_success_hit_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[30s])) by (project, network, category, connector)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache GET success-hit duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1349 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector))",
       "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector))",
       "legendFormat": "p99 - {{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache GET success-miss total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1359 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_cache_get_success_miss_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[1m])) by (project, network, category, connector)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache GET success-miss duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1359 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector))",
       "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector))",
       "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}"
      }
     ]
    },
    {
     "title": "Cache GET error total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1369 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_cache_get_error_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",error!~\".*(ErrRecordNotFound|MissingData).*\",project=~\"${project:regex}\"}[1m])) by (region, project, network, category, connector, error)",
       "legendFormat": "{{region}} {{project}}, {{network}}, {{category}}, {{connector}}, {{error}}"
      }
     ]
    },
    {
     "title": "Cache GET error duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1369 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",error!~\".*(ErrRecordNotFound|MissingData).*\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector, error))",
       "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{error}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",error!~\"ErrRecordNotFound.*\",project=~\"${project:regex}\"}[30s])) by (le, project, network, category, connector, error))",
       "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Misbehavior efficiency (vs total)",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1380 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "bottomk(30, \n  sum by (network, category, finality) (\n    erpc_consensus_misbehavior_detected_total{\n      network=~\"${network:regex}\",\n      project=~\"${project:regex}\",\n      category=~\"${category:regex}\"\n    })\n  /\n  sum by (network, category, finality) (\n    erpc_consensus_total{\n      network=~\"${network:regex}\",\n      project=~\"${project:regex}\",\n      category=~\"${category:regex}\"\n    })\n)",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Total consensus operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1391 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_total{cluster=~\"${cluster:regex}\",network=~\"${network:regex}\",project=~\"${project:regex}\",category=~\"${category:regex}\"}[1m])) by (network, category)",
       "legendFormat": "{{network}}, {{category}}"
      }
     ]
    },
    {
     "title": "Avg. consensus agreements per operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1391 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(erpc_consensus_agreement_count_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (le, network, category, finality))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}"
      }
     ]
    },
    {
     "title": "Total consensus responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1399 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_responses_collected_count{cluster=~\"${cluster:regex}\",network=~\"${network:regex}\",project=~\"${project:regex}\",category=~\"${category:regex}\",finality=~\"${finality:regex}\"}[1m])) by (network, category, finality, vendors) > 0",
       "legendFormat": "{{network}}, {{category}}, {{finality}}, {{vendors}}"
      }
     ]
    },
    {
     "title": "Avg. consensus responses per operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1399 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(erpc_consensus_responses_collected_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (le, network, category, short_circuited, finality))",
       "legendFormat": "{{network}}, {{category}}, {{finality}}, short-circuited={{short_circuited}}"
      }
     ]
    },
    {
     "title": "Total consensus misbehaviors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1407 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_misbehavior_detected_total{\n    region=~\"${region:regex}\",\n    cluster=~\"${cluster:regex}\",\n    project=~\"${project:regex}\",\n    network=~\"${network:regex}\",\n    upstream=~\"${upstream:regex}\",\n    category=~\"${category:regex}\",\n    finality=~\"${finality:regex}\"\n}[1m])) by (network, upstream, category, finality, response_type, larger_than_consensus) > 0",
       "legendFormat": "{{network}}, {{upstream}}, {{category}}, {{finality}}, type={{response_type}} larger={{larger_than_consensus}}"
      }
     ]
    },
    {
     "title": "Total consensus short-circuits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1407 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_short_circuit_total{network=~\"${network:regex}\",project=~\"${project:regex}\",category=~\"${category:regex}\"}[1m])) by (network, category, reason, finality) > 0",
       "legendFormat": "{{network}}, {{category}}, {{reason}}, {{finality}} "
      }
     ]
    },
    {
     "title": "Total consensus errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1415 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_errors_total{network=~\"${network:regex}\",project=~\"${project:regex}\",category=~\"${category:regex}\"}[1m])) by (network, category, category, error, finality) > 0",
       "legendFormat": "{{network}}, {{category}}, {{finality}}, {{error}}"
      }
     ]
    },
    {
     "title": "Total consensus cancellations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1415 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(erpc_consensus_cancellations_total{network=~\"${network:regex}\",project=~\"${project:regex}\",category=~\"${category:regex}\"}[1m])) by (network, category, phase, finality) > 0",
       "legendFormat": "{{network}}, {{category}}, {{phase}}, {{finality}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks Heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Access Blocks Heatmap Top 20 (Cacheable)",
     "type": "heatmap",
     "gridPos": { "h": 17, "w": 16, "x": 0, "y": 15320 },
     "targets": [
      {
       "expr": "topk(20, sum by (bucket, network) (\n  increase(erpc_network_evm_block_range_requested_total{\n    network=~\"${network:regex}\",network!~\"${ignore_network:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",vendor=~\"${vendor:regex}\",\n    category=~\"(eth_getBlockByNumber|eth_getBlockByHash|eth_blockNumber|eth_getLogs|eth_getTransactionByHash|eth_getTransactionReceipt|eth_getBlockReceipts)\"\n  }[$__range])\n))",
       "legendFormat": "{{bucket}} {{network}}"
      }
     ]
    },
    {
     "title": "Top Block Buckets by Network (Cacheable)",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 8, "x": 16, "y": 15320 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,\n  (\n    sum by (network, bucket) (\n      increase(erpc_network_evm_block_range_requested_total{\n        network=~\"${network:regex}\",network!~\"${ignore_network:regex}\",\n        category=~\"${category:regex}\",\n        project=~\"${project:regex}\",\n        vendor=~\"${vendor:regex}\",\n        # bucket!~\"(TIP|LATEST|FUTURE|FINALIZED)\",\n        category=~\"(eth_getBlockByNumber|eth_getBlockByHash|eth_getLogs|eth_blockNumber|eth_getTransactionByHash|eth_getTransactionReceipt|eth_getBlockReceipts)\"\n      }[$__range])\n    )\n  )\n)",
       "legendFormat": "{{network}} / {{bucket}}"
      }
     ]
    },
    {
     "title": "Access Blocks Heatmap by Method (Non-cacheable)",
     "type": "heatmap",
     "gridPos": { "h": 17, "w": 16, "x": 0, "y": 15337 },
     "targets": [
      {
       "expr": "sum by (category, bucket) (\n  increase(erpc_network_evm_block_range_requested_total{\n    network=~\"${network:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",\n    category!~\"(eth_getBlockByNumber|eth_getBlockByHash|eth_getLogs|eth_blockNumber|eth_getTransactionByHash|eth_getTransactionReceipt|eth_getBlockReceipts)\"\n  }[5m])\n)",
       "legendFormat": "{{category}} / {{bucket}}"
      }
     ]
    },
    {
     "title": "Top Block Buckets (Non-cacheable)",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 8, "x": 16, "y": 15337 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20,\n  sum by (network, bucket) (\n    increase(erpc_network_evm_block_range_requested_total{\n      network=~\"${network:regex}\",category=~\"${category:regex}\",project=~\"${project:regex}\",\n      category!~\"(eth_getBlockByNumber|eth_getBlockByHash|eth_getLogs|eth_blockNumber|eth_getTransactionByHash|eth_getTransactionReceipt|eth_getBlockReceipts)\"\n    }[$__range])\n  )\n)",
       "legendFormat": "{{network}} / {{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate Limiters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate-limit budget MaxCount",
     "type": "timeseries",
     "description": "Dynamically tuned value for maxCount of different rate limit budgets. NOTE This value is SUM of all replicas (in a multiple container setup)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26254 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (budget, method) (erpc_rate_limiter_budget_max_count{})\n",
       "legendFormat": "{{budget}}, config_method={{method}}"
      }
     ]
    },
    {
     "title": "Project-level RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26263 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{origin=\"project\",project=~\"${project:regex}\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, budget)",
       "legendFormat": "{{project}}, {{network}}, {{budget}}"
      }
     ]
    },
    {
     "title": "Network-level RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26263 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{origin=\"network\",project=~\"${project:regex}\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",budget!=\"<remote>\"}[1m])) by (project, network, user)",
       "legendFormat": "{{project}}, {{network}}, {{user}}"
      }
     ]
    },
    {
     "title": "Upstream remote RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26276 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{origin=\"upstream\",budget=\"<remote>\",project=~\"${project:regex}\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, vendor)",
       "legendFormat": "{{project}}, {{network}}, {{vendor}}"
      }
     ]
    },
    {
     "title": "Upstream self-imposed RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26276 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{origin=\"upstream\",budget!=\"<remote>\",project=~\"${project:regex}\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, vendor)",
       "legendFormat": "{{project}}, {{network}}, {{vendor}}"
      }
     ]
    },
    {
     "title": "Auth-level RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26289 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{origin=\"auth\",project=~\"${project:regex}\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, user, auth)",
       "legendFormat": "{{project}}, {{network}}, {{user}}, {{auth}}"
      }
     ]
    },
    {
     "title": "Method RPS rate limits",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26289 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limits_total{network=~\"${network:regex}\",project=~\"${project:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category, origin, budget)",
       "legendFormat": "origin={{origin}}, project={{project}}, {{network}}, {{category}}, budget={{budget}}"
      }
     ]
    },
    {
     "title": "Failopen Rate Limiter Passes RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26302 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(erpc_rate_limiter_failopen_total{network=~\"${network:regex}\",project=~\"${project:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category, origin, budget)",
       "legendFormat": "{{project}}, {{network}}, {{category}}, {{budget}}"
      }
     ]
    }
   ]
  },
  {
   "title": "evm eth_getLogs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "eth_getLogs P99 ranges",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5632 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(erpc_network_evm_get_logs_range_requested_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (le, project, network, user, finality))",
       "legendFormat": "{{project}}, {{network}}, {{user}}, {{finality}}"
      }
     ]
    },
    {
     "title": "eth_getLogs P50 ranges",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5632 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(erpc_network_evm_get_logs_range_requested_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",project=~\"${project:regex}\",finality=~\"${finality:regex}\"}[1m])) by (le, project, network, user, finality))",
       "legendFormat": "{{project}}, {{network}}, {{user}}, {{finality}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth failures total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93815 },
     "targets": [
      {
       "expr": "sum(increase(erpc_auth_failed_total{\n      cluster=~\"${cluster:regex}\",\n      region=~\"${region:regex}\"\n}[$__interval])) by (project, region, strategy, reason, agent_name) > 0",
       "legendFormat": "{{project}} {{region}} {{strategy}} {{reason}} {{agent_name}}"
      }
     ]
    }
   ]
  }
 ]
}