{
 "title": "Ponder",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin method duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, max by(le, method) (increase(ponder_database_method_duration_bucket{service=\"admin\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Sync store method duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, max by(le, method) (increase(ponder_database_method_duration_bucket{service=\"sync\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Indexing method duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, max by(le, method) (increase(ponder_database_method_duration_bucket{service=\"indexing\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "[Postgres] Query rate",
   "type": "timeseries",
   "description": "Rate of queries submitted to the database",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pool) (rate(ponder_postgres_query_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Postgres] Queue size",
   "type": "timeseries",
   "description": "Number of query requests waiting for an available connection",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pool) (rate(ponder_postgres_query_queue_size[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[SQLite] Query rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by(database) (rate(ponder_sqlite_query_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Real-time sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latest block number",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ponder_realtime_latest_block_number",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "RPC request duration (p95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, ponder_realtime_rpc_request_duration_bucket)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC request duration (mean)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, ponder_realtime_rpc_request_duration_bucket)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(rpc_requests_total[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rpc_requests_total)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Since latest block timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - ponder_realtime_latest_block_timestamp{network=\"$networks\"}",
     "legendFormat": "Block number"
    }
   ]
  },
  { "title": "Historical sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Historical sync progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ponder_historical_completed_blocks / ponder_historical_total_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC request duration (mean)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, ponder_historical_rpc_request_duration_bucket)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC request duration (p95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, ponder_historical_rpc_request_duration_bucket)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ponder_default_process_resident_memory_bytes",
     "legendFormat": "Total (RSS)"
    },
    {
     "expr": "ponder_default_nodejs_heap_size_total_bytes",
     "legendFormat": "Heap total (V8)"
    },
    {
     "expr": "ponder_default_nodejs_heap_size_used_bytes",
     "legendFormat": "Heap used (V8)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ponder_default_process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(ponder_default_process_cpu_user_seconds_total[$__rate_interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(ponder_default_process_cpu_system_seconds_total[$__rate_interval])",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ponder_default_nodejs_eventloop_lag_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ponder_default_nodejs_gc_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}