/**
 * Enum representing all risk areas (defense areas) that can be analyzed for a DAO
 */
export enum RiskAreaEnum {
  SPAM_RESISTANCE = "SPAM RESISTANCE",
  ECONOMIC_SECURITY = "ECONOMIC SECURITY",
  SAFEGUARDS = "SAFEGUARDS",
  CONTRACT_SAFETY = "CONTRACT SAFETY",
  RESPONSE_TIME = "RESPONSE TIME",
  GOV_FRONTEND_RESILIENCE = "GOV FRONT-END RESILIENCE",
}
