/**
 * Enum representing all risk areas that can be analyzed for a DAO
 */
export enum RiskAreaEnum {
  SPAM_VULNERABLE = "SPAM VULNERABLE",
  ATTACK_PROFITABILITY = "ATTACK PROFITABILITY",
  SAFEGUARDS = "SAFEGUARDS",
  HACKABLE = "HACKABLE",
  RESPONSE_TIME = "RESPONSE TIME",
  GOV_FRONTEND_VULNERABILITY = "GOV FRONT-END VULNERABILITY",
}
