import figma from "@figma/code-connect";
import React from "react";

import { SimpleProgressBar } from "./SimpleProgressBar";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SimpleProgressBar,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=11068%3A13611",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "labelPosition": figma.enum('label position', {
      //   "top": "top",
      //   "left": "left",
      //   "right": "right",
      //   "bottom": "bottom"
      // })
    },
    example: (props) => <SimpleProgressBar percentage={/* TODO */} />,
  },
);
