import figma from "@figma/code-connect";
import React from "react";

import { FormLabel } from "./FormLabel";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FormLabel,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=11068%3A13592",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "hasValue": figma.boolean('hasValue'),
      // "isColorful": figma.boolean('isColorful')
    },
    example: (props) => <FormLabel children={""} />,
  },
);
