
export enum MetricTypesEnum {
  TOTAL_SUPPLY = "TOTAL_SUPPLY",
  DELEGATED_SUPPLY = "DELEGATED_SUPPLY",
  CEX_SUPPLY = "CEX_SUPPLY",
  DEX_SUPPLY = "DEX_SUPPLY",
  LENDING_SUPPLY = "LENDING_SUPPLY",
  CIRCULATING_SUPPLY = "CIRCULATING_SUPPLY",
  TREASURY = "TREASURY",
  PROPOSALS = "PROPOSALS",
  ACTIVE_SUPPLY = "ACTIVE_SUPPLY",
  VOTES = "VOTES",
  AVERAGE_TURNOUT = "AVERAGE_TURNOUT",
}

export const metricTypeArray = Object.values(MetricTypesEnum);

export const SECONDS_PER_DAY = 86400;
export const MILLISECONDS_PER_SECOND = 1000;
export const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60;
export const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_SECOND * 60 * 60;
export const MILLISECONDS_PER_DAY = SECONDS_PER_DAY * MILLISECONDS_PER_SECOND;
