FROM prom/prometheus:latest
COPY prometheus.yml /etc/prometheus/prometheus.yml.tmpl
COPY alerts.yml /etc/prometheus/alerts.yml
COPY entrypoint.prometheus.sh /entrypoint.sh
USER root
RUN chmod +x /entrypoint.sh && apk add --no-cache gettext
ENTRYPOINT ["/entrypoint.sh"]
