name: GraphQL Client Codegen

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine.outputs.environment }}
      railway_token: ${{ steps.determine.outputs.railway_token }}
    steps:
      - name: Determine environment and token
        id: determine
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
          echo "Deploying to: $([ '${{ github.ref }}' == 'refs/heads/main' ] && echo 'production' || echo 'dev')"

  codegen:
    runs-on: ubuntu-latest
    needs: [environment]
    environment: ${{ needs.environment.outputs.environment }}
    env:
      ANTICAPTURE_GRAPHQL_ENDPOINT: ${{ secrets.GATEWAY_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run GraphQL codegen
        run: pnpm client codegen

      - name: Build GraphQL client
        run: pnpm client build
