name: Label PR Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'apps/api/**/*'
              - 'apps/address-enrichment/**/*'
            indexer:
              - 'apps/indexer/**/*'
            offchain:
              - 'apps/offchain-indexer/**/*'
            dashboard:
              - 'apps/dashboard/**/*'
              - 'packages/*-client/**/*'
            gateway:
              - 'apps/api-gateway/**/*'
            gateful:
              - 'apps/gateful/**/*'

      - name: Add API label
        if: ${{ steps.changes.outputs.api == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: API

      - name: Add indexer label
        if: ${{ steps.changes.outputs.indexer == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Indexer

      - name: Add offchain label
        if: ${{ steps.changes.outputs.offchain == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Offchain

      - name: Add dashboard label
        if: ${{ steps.changes.outputs.dashboard == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Dashboard

      - name: Add gateway label
        if: ${{ steps.changes.outputs.gateway == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Gateway

      - name: Add gateful label
        if: ${{ steps.changes.outputs.gateful == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Gateful

      - name: Add Relayer label
        if: ${{ steps.changes.outputs.relayer == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Relayer
