import figma from "@figma/code-connect";
import React from "react";

import { ButtonFilter } from "./ButtonFilter";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonFilter,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=10682%3A14018",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "status": figma.enum('status', {
      //   "default": "default",
      //   "hover": "hover",
      //   "on click": "on-click"
      // }),
      // "type": figma.enum('type', {
      //   "category": "category",
      //   "amount": "amount",
      //   "address": "address"
      // }),
      // "isLeft": figma.boolean('isLeft')
    },
    example: (props) => <ButtonFilter onClick={() => {}} />,
  },
);
