import figma from "@figma/code-connect";
import { Row } from "@tanstack/react-table";
import React from "react";

import { ExpandableData, ExpandButton } from "./ExpandButton";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ExpandButton,
  "https://www.figma.com/design/DEKMQifA8YOb3oxznHboSY/%F0%9F%93%81-Orbit-UI?node-id=4%3A5683",
  {
    props: {},
    example: (props) => (
      <ExpandButton
        row={{} as unknown as Row<ExpandableData>}
        enableExpanding={false}
      />
    ),
  },
);
